import 'package:ala_magang/shared/shared.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:supercharged/supercharged.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'dart:math' as math;
import 'package:timeago/timeago.dart' as ago;

part 'bottomnavigationbar.dart';
part 'promocard.dart';
part 'foodcard.dart';
part 'categoriesFoodCard.dart';
part 'shopcard.dart';
part 'rating_bar.dart';
part 'chatcard.dart';
part 'customtabbar.dart';
part 'blogcard.dart';
part 'feedcard.dart';
part 'FoodCardAdd.dart';
part 'menucookcard.dart';
